
on:
  push:
    branches:
      - "main"
  workflow_dispatch: {}

jobs:
  self-test:
    runs-on: "ubuntu-latest"

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: "write"      # to deploy to Pages
      id-token: "write"   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    steps:

      # Checkout your repository
      - uses: "actions/checkout@v4"

      # Optional: Install your preferred Python version and dependencies and set up caches
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
          cache: "pip"

      # Run the action
      - uses: "./" # Yeicor/cadquery-action@v#
        with:
          scripts: "demo.py"
          # formats: "STL|STEP|AMF|SVG|TJS|DXF|VRML|VTP|3MF|GLTF"
          # website: "."
          # website-screenshot: "true"