
on:
  push:
    branches:
      - "main"
  workflow_dispatch: {}

jobs:
  self-test:
    runs-on: "ubuntu-latest"
    steps:

      # Checkout the repository
      - uses: "actions/checkout@v4"

      # Optional: Install your preferred Python version and dependencies

      # Run the action
      - uses: "./"
        with:
          scripts: "demo.py"